apiVersion: v2
name: infrastructure
description: A Helm chart for Kubernetes

type: application


version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: postgresql
    version: 15.4.0
    repository: https://charts.bitnami.com/bitnami
  - name: keycloak
    version: 21.3.1
    repository: https://charts.bitnami.com/bitnami



