apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-postgresql-creds
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-99"
data:
  username: {{ .Values.postgresql.auth.postgresUser | b64enc }}
  password: {{ .Values.postgresql.auth.postgresPassword | b64enc }}