apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-keycloak-admin-creds
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-99"
data:
  username: {{ .Values.keycloak.auth.adminUser | b64enc }}
  password: {{ .Values.keycloak.auth.adminPassword | b64enc }}