name: devRelease(tag)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
  workflow_call:
    inputs:
      tag:
        description: 'Tag to release'
        type: string
        required: true
    secrets:
      PAT:
        description: 'Personal Access Token'
        required: true
      KUBECONFIG_DEV:
        description: 'Kubeconfig for dev cluster'
        required: true

jobs:
  tag-repositories:
    name: Tag repositories
    strategy:
      matrix:
        repository:
          - 'noootaaa/frontend'
          - 'noootaaa/backend'
    uses: noootaaa/infrastructure/actions/.github/workflows/tag-repositories@main
    with:
      tag: ${{ inputs.tag }}
      repository: ${{ matrix.repository }}
      branch: 'main'