name: CI/Build Docker Image

on:
  workflow_call:
    inputs:
      dockerfile:
        description: "The path to the Dockerfile"
        required: false
        type: string
        default: "Dockerfile"
      context:
        description: "The build directory of the image"
        required: false
        type: string
        default: "."
      image-name:
        required: true
        type: string
        description: "The name of the image"
      build-args:
        required: false
        type: string
        description: "List of build args"
      tag:
        required: false
        type: string
        description: "The git tag to checkout"
      repository:
        required: false
        type: string
        description: "The repository to checkout"
    secrets:
      CONTAINER_REGISTRY_TOKEN:
        required: true
      CONTAINER_REGISTRY_USERNAME:
        required: true
      CONTAINER_REGISTRY_ENDPOINT:
        required: true
      PAT:
        required: true

  workflow_dispatch:
    inputs:
      dockerfile:
        description: "The path to the Dockerfile"
        required: false
        type: string
        default: "Dockerfile"
      context:
        description: "The build directory of the image"
        required: false
        type: string
        default: "."
      image-name:
        required: true
        type: string
        description: "The name of the image"
      build-args:
        required: false
        type: string
        description: "List of build args"
      tag:
        required: false
        type: string
        description: "The git tag to checkout"
      repository:
        required: true
        type: string
        description: "The repository to checkout"


jobs:
  docker-build-and-push:
    name: Docker build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set version
        id: set-version
        run: echo "VERSION=${{ inputs.tag }}" >> $GITHUB_ENV
      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }} 
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context }}
          build-args: ${{ inputs.build-args }}
          tags: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/${{ inputs.repository }}:${{ env.VERSION }}
    