name: tagRepositories(tag, branch, repository)

on:
  workflow_call:
    inputs:
      tag:
        description: 'Tag to release'
        type: string
        required: true
      branch:
        description: 'Branch to tag'
        type: string
        required: true
      repository:
        description: 'Repository to release'
        required: true
        type: string
    secrets:
      PAT:
        description: 'Personal Access Token'
        required: true


jobs:
  tag-repositories:
    runs-on: ubuntu-latest
    name: Tag Repository
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.branch }}
          token: ${{ secrets.PAT }}
      - name: Tag Repo and push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag -a ${{ inputs.tag }} -m "Release ${{ inputs.tag }}"
          git push origin ${{ inputs.tag }}